<a href="https://colab.research.google.com/github/Beamer2000/SQL-Portfoilio-Project/blob/main/Abimbola_Edubridge_cohort_May25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# INTRODUCTION TO PYTHON PROGRAMMING

Lets get started!!!

In [210]:
"Edubridge"

'Edubridge'

In [211]:
school = "Edubridge"

In [212]:
print(school)

Edubridge


In [213]:
name = 'Aishat'
age = 20

In [214]:
colour = "green"
number = 1

In [215]:
print(age)
print(name)
print(colour)
print(number)

20
Aishat
green
1


### Python String (str)

In [216]:
name = "deborah"

In [217]:
len(name)

7

In [218]:
# indexing: indexing starts from 0
name

'deborah'

In [219]:
name[0]

'd'

In [220]:
name[6]

'h'

In [221]:
# slicing : variable[start_index:end_index + 1]
name[0:3]

'deb'

In [222]:
name[1:4]

'ebo'

In [223]:
name[1:]

'eborah'

In [224]:
type(name)

str

In [225]:
# string methods; methods are functions specific to a string
dir(str)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'stri

In [226]:
help(str)

Help on class str in module builtins:

class str(object)
 |  str(object='') -> str
 |  str(bytes_or_buffer[, encoding[, errors]]) -> str
 |
 |  Create a new string object from the given object. If encoding or
 |  errors is specified, then the object must expose a data buffer
 |  that will be decoded using the given encoding and error handler.
 |  Otherwise, returns the result of object.__str__() (if defined)
 |  or repr(object).
 |  encoding defaults to sys.getdefaultencoding().
 |  errors defaults to 'strict'.
 |
 |  Methods defined here:
 |
 |  __add__(self, value, /)
 |      Return self+value.
 |
 |  __contains__(self, key, /)
 |      Return bool(key in self).
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __format__(self, format_spec, /)
 |      Return a formatted version of the string as described by format_spec.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getitem__(self, key, /)
 |      Return self[key].
 |
 |  __getnewargs__(...)
 |
 |  _

In [227]:
name = name.capitalize()

In [228]:
name

'Deborah'

In [229]:
name = name.upper()

In [230]:
print(name)

DEBORAH


In [231]:
name.endswith("H")


True

In [232]:
name.endswith(name[6])


True

In [233]:
name.endswith(name[-1])

True

In [234]:
name[-1]

'H'

In [235]:
name[-3:]

'RAH'

### Python int AND float

In [236]:
person = "Abracadabra"
weight = 70.5
height = 5

In [237]:
print(type(weight))
print(type(height))

<class 'float'>
<class 'int'>


In [238]:
type(person)

str

In [239]:
#  mathematical operators:
# +
# -
# *
# **
# /
# //
# %

In [240]:
operand1 = 10
operand2 = 2

In [241]:
print(operand1 + operand2)
print(operand1 - operand2)
print(operand1 / operand2)
print(operand1 * operand2)
print(operand1 ** operand2)

12
8
5.0
20
100


In [242]:
operand1 // operand2 # floor division

5

In [243]:
print(5/2)
print(5//2)

2.5
2


In [244]:
# modulo
print(5/2)
print(5%2)

2.5
1


In [245]:
# List Contains a collection of python objects
# [] - bracket
# () - parenthesis
# {} - curly braces

In [246]:
student1 =  "Deborah"
student2 = 'Olumide'
student3 = 'Sola'

In [247]:
student_names = ["Deborah", 'Olumide', 'Sola']

In [248]:
student_names [0]

'Deborah'

In [249]:
student_names [1]

'Olumide'

In [250]:
student_names [2]

'Sola'

In [251]:
len(student_names [0])

7

In [252]:
len(student_names [1])

7

In [253]:
student1.upper()

'DEBORAH'

In [254]:
student_names[0].upper()

'DEBORAH'

In [255]:
student_names[2].lower()

'sola'

In [256]:
student_names[2][0]

'S'

In [257]:
help(list)

Help on class list in module builtins:

class list(object)
 |  list(iterable=(), /)
 |
 |  Built-in mutable sequence.
 |
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |
 |  Methods defined here:
 |
 |  __add__(self, value, /)
 |      Return self+value.
 |
 |  __contains__(self, key, /)
 |      Return bool(key in self).
 |
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __getitem__(self, index, /)
 |      Return self[index].
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate sign

In [258]:
student_names.append("Damilola")

In [259]:
student_names

['Deborah', 'Olumide', 'Sola', 'Damilola']

In [260]:
name  = 'seYON'

In [261]:
name

'seYON'

In [262]:
name.title()

'Seyon'

In [263]:
name = name.title()

In [264]:
name

'Seyon'

In [265]:
# call out the number of items in a list
len(student_names)

4

In [266]:
# Redefining a variable
student_names2 = ['Deborah', 16, 'Olumide', 70, "Sola", 5, "Damilola", 18]

In [267]:
# To retrieve the name of the second student
student_names2[2]

'Olumide'

In [268]:
# To retrieve the age of the third student
student_names2[5]

5

In [269]:
# To remove the last student in the student list
student_names2.pop()
print(student_names2)
student_names2.pop()
print(student_names2)

['Deborah', 16, 'Olumide', 70, 'Sola', 5, 'Damilola']
['Deborah', 16, 'Olumide', 70, 'Sola', 5]


In [270]:
student_names2.index("Olumide")

2

In [271]:
student_names2.remove('Olumide')

In [272]:
student_names2

['Deborah', 16, 70, 'Sola', 5]

In [273]:
student_names2[2]

70

In [274]:
student_names2.remove(70)

In [275]:
student_names2

['Deborah', 16, 'Sola', 5]

In [276]:
student_names2.remove(5)

In [277]:
student_names2.remove('Sola')

In [278]:
student_names2

['Deborah', 16]

In [279]:
student_names2.remove(16)

In [280]:
student_names2.remove('Deborah')

In [281]:
student_names2

[]

In [282]:
student_names2.append('Adebayo')
student_names2.append(17)

In [283]:
student_names2

['Adebayo', 17]

In [284]:
# To replace name ir reassign item
# list support mutability
student_names2[0] = "Daniel"
student_names2[1] = 20



In [285]:
student_names2

['Daniel', 20]

### Python Tuple

In [286]:
new_students = ('Adebayo', 20)

In [287]:
new_students

('Adebayo', 20)

In [288]:
type(new_students)

tuple

### Python Set

In [289]:
unique_numbers = {0, 1, 5, 8, 7, 1, 1, 7}
unique_numbers

{0, 1, 5, 7, 8}

In [290]:
dir (set)

['__and__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iand__',
 '__init__',
 '__init_subclass__',
 '__ior__',
 '__isub__',
 '__iter__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__or__',
 '__rand__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__ror__',
 '__rsub__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__xor__',
 'add',
 'clear',
 'copy',
 'difference',
 'difference_update',
 'discard',
 'intersection',
 'intersection_update',
 'isdisjoint',
 'issubset',
 'issuperset',
 'pop',
 'remove',
 'symmetric_difference',
 'symmetric_difference_update',
 'union',
 'update']

In [291]:
s1 = {1, 2, 5}
s2 = {1, 5, 6}

In [292]:
s1.union(s2)

{1, 2, 5, 6}

In [293]:
s1.difference(s2)

{2}

### Python Dictionary

In [294]:
student_names2 = ['Deborah', 16, 'Olumide', 70, "Sola", 5, "Damilola", 18]

In [295]:
def_students = {"Names":  ['Deborah','Olumide',"Sola","Damilola"], "Age": [16, 70, 5, 18]}

In [296]:
type(def_students)

dict

In [297]:
len(def_students)

2

In [298]:
def_students['Names']

['Deborah', 'Olumide', 'Sola', 'Damilola']

In [299]:
def_students['Names'][-1]

'Damilola'

### Type Conversion

In [300]:
s = 'Great'
sn = '30'
n = 20

In [301]:
sn

'30'

In [302]:
int(sn)

30

In [303]:
# type casting: changing from one type to another
int(sn) + n

50

In [304]:
l = [20, 500, 20, 1000,30]
l

[20, 500, 20, 1000, 30]

In [305]:
set(l)

{20, 30, 500, 1000}

In [306]:
denomination = set(l)
denomination

{20, 30, 500, 1000}

In [307]:
tuple(l)

(20, 500, 20, 1000, 30)

In [308]:
# keys, values, items

In [309]:
alphabets = {1: 'a', 2: 'b', 3: 'c'}

In [310]:
alphabets.values()

dict_values(['a', 'b', 'c'])

In [311]:
list(alphabets.values())

['a', 'b', 'c']

In [312]:
alphabets.items()

dict_items([(1, 'a'), (2, 'b'), (3, 'c')])

In [313]:
# Iterables is a python object that contains collection of values
list(alphabets.items())

[(1, 'a'), (2, 'b'), (3, 'c')]

# CONTROL FLOW
* Conditional statement (`if`)
* Looping statement (`for` and `while`)

# Conditional Statement

In [314]:
# import random library
import random

In [315]:
help(random.choice)

Help on method choice in module random:

choice(seq) method of random.Random instance
    Choose a random element from a non-empty sequence.



In [316]:
number_source = list(range(1, 11))
number_source

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [317]:
computer = random.choice(number_source)

In [318]:
computer

5

In [319]:
# Logic operators >,  <, <=, >=, ==, !=
n1 = 3
n2 = 4

n1 < n2

True

In [320]:
damilola2 = 9
if damilola2 == computer:
  print("Nice guess!!!")
else:
  print("Try again")

Try again


In [321]:
# and, or and not

In [322]:
statement1 = 3 < 5
statement2 = 4 < 5

In [323]:
# or
print(True or True)
print(True or False)
print(False or True)
print(False or False)

True
True
True
False


In [324]:
# and
print(True and True)
print(True and False)
print(False and True)
print(False and False)

True
False
False
False


In [325]:
statement1 or statement2

True

In [326]:
score = 75

In [327]:
# <= 39 = 'F'
# >= 40 < 50 = 'E'
# >= 50 < 60 = 'C'
# >= 60 < 70 = 'B'
# >= 70 = 'A'

In [328]:
if score <= 39:
  print ('F')
elif score >= 40 and  score < 50:
  print ('E')
elif score >= 50 and  score < 60:
  print ('C')
elif score >= 60 and  score < 70:
  print ('B')
else:
  print('A')

A


## Looping Statement

In [329]:
num = list(range(1,11))
num

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [330]:
for n in num:
  print(n)

1
2
3
4
5
6
7
8
9
10


In [331]:
import time

In [332]:
for n in num:
  print(n)
  time.sleep(2)

1
2
3
4
5
6
7
8
9
10


In [333]:
rand_nums = [1,2,3]
rand_nums[1] = 4
rand_nums

[1, 4, 3]

In [334]:
num

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [335]:
for n in num:
  index = num.index(n)
  num[index] = n**2

In [336]:
num

[1, 16, 81, 4, 25, 36, 49, 64, 9, 100]

In [337]:
for n in num:
  print(n**2)

1
256
6561
16
625
1296
2401
4096
81
10000


In [338]:
num.sort()
num

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [339]:
num.sort(reverse=True)
num

[100, 81, 64, 49, 36, 25, 16, 9, 4, 1]

In [340]:
num = list(range(1,11))
for n in num:
  i = num.index(n)
  num[i] = n**2

In [341]:
# list comprehension
num = [n**2 for n in num]
num

[1, 256, 6561, 16, 625, 1296, 2401, 4096, 81, 10000]

## Python User Defined Functions

In [342]:
dami1 = 6
dami2 = 8
print(dami1+dami2)

14


In [343]:
seyon1 = 4
seyon2 = 8
print(seyon1+seyon2)

12


In [344]:
def addition_calculator(parameter1, parameter2):
  return parameter1 + parameter2

In [345]:
Dami = addition_calculator(6, 8) # 6 and 8 are called arguments in a function call
Dami

14

In [346]:
Seyon = addition_calculator(4, 8)
Seyon

12

In [347]:
addition_calculator(Dami, Seyon)

26

In [348]:
Dami + Seyon

26

In [349]:
square_items = ([1,2,3,6])
square_items= [n**2 for n in square_items]
square_items

[1, 4, 9, 36]

In [350]:
def square_list(list_nums):
     return [n**2 for n in list_nums]

In [351]:
square_list([6, 9, 4])

[36, 81, 16]

In [352]:
def uppercase_function(names):
  return [first_name.upper() for first_name in names]

In [353]:
list_argument = ["Chinenye", "Esther", 'Daniel', 'Debola']
uppercase_function(list_argument)

['CHINENYE', 'ESTHER', 'DANIEL', 'DEBOLA']

## Some Special Function

In [354]:
num = list(range(1,11))
for n in num:
  i = num.index(n)
  num[i] = n**2

In [355]:
num = [100, 105, 250]
list(enumerate(num))

[(0, 100), (1, 105), (2, 250)]

In [356]:
x, y = (1,50)
print(x)
print(y)

1
50


In [357]:
for t in enumerate(num):
  print(t)

(0, 100)
(1, 105)
(2, 250)


In [358]:
for i, value in enumerate(num):
  num[1] = value **2

num

[100, 62500, 250]

In [359]:
nums = [100, 200, 300]
enumerate(nums)

In [360]:
list(enumerate(nums))

[(0, 100), (1, 200), (2, 300)]

In [361]:
# tuple unpacking
a,b,c,d,f =  (1,2,3,4,5)

In [362]:
a

1

In [363]:
for i, value in enumerate(nums):
  nums[i] = value**2

In [364]:
nums

[10000, 40000, 90000]

## Some string Important methods
split, join

In [365]:
s = "2000 01 01"

In [366]:
s_list = s.split(' ')
s_list

['2000', '01', '01']

In [367]:
empty_string = '-'
len(empty_string)

1

In [368]:
empty_string.join(s_list)

'2000-01-01'

In [369]:
from types import FunctionType


## Python Numpy

In [370]:
import numpy as np

In [371]:
# 1D list
age = [20, 50, 23, 80, 15]

In [372]:
age [-1]

15

In [373]:
student_info = [["Ronke", 'Uzezi', 'Ada', "Josh"], [15, 20, 25, 12]]

In [374]:
student_info[0]

['Ronke', 'Uzezi', 'Ada', 'Josh']

In [375]:
student_info[0][1]

'Uzezi'

In [376]:
student_info[1][1]

20

## Converting python list to numpy array

In [377]:
age

[20, 50, 23, 80, 15]

In [378]:
[n + 1 for n in age]

[21, 51, 24, 81, 16]

In [379]:
age_arr = np.array(age)
age_arr

array([20, 50, 23, 80, 15])

In [380]:
# element wise operation: 1 is added to each element in the array
age_arr + 1

array([21, 51, 24, 81, 16])

In [381]:
a = np.array([1,2,3])
b = np.array ([4,5,6])

In [382]:
a

array([1, 2, 3])

In [383]:
b

array([4, 5, 6])

In [384]:
a * b

array([ 4, 10, 18])

In [385]:
# the number of items in a numpy array
a.shape

(3,)

In [386]:
a.size

3

In [387]:
# function in 1D array

age_arr

array([20, 50, 23, 80, 15])

In [388]:
np.mean(age)

np.float64(37.6)

In [389]:
age_arr.mean()

np.float64(37.6)

In [390]:
#2D

student_info

[['Ronke', 'Uzezi', 'Ada', 'Josh'], [15, 20, 25, 12]]

In [391]:
student_info_arr = np.array(student_info)

print(student_info_arr)

[['Ronke' 'Uzezi' 'Ada' 'Josh']
 ['15' '20' '25' '12']]


In [392]:
student_info_arr[0]

array(['Ronke', 'Uzezi', 'Ada', 'Josh'], dtype='<U21')

In [393]:
student_info_arr[0, 0]

np.str_('Ronke')

In [394]:
student_info_arr.shape

(2, 4)

In [395]:
student_info_arr.size

8

In [396]:
student_info_arr[1, 2]

np.str_('25')

In [397]:
student_info_arr[:, :2]

array([['Ronke', 'Uzezi'],
       ['15', '20']], dtype='<U21')

In [398]:
student_info_arr[1]

array(['15', '20', '25', '12'], dtype='<U21')

In [399]:
student_info_arr[1].astype(int).max()

np.int64(25)

## Pandas

[['Ronke', 'Uzezi', 'Ada', 'Josh'], [15, 20, 25, 12]]

In [400]:
import pandas as pd

In [401]:
student_info_d = {'Names': ['Ronke', 'Uzezi', 'Ada', 'Josh'], 'Age': [15, 20, 25, 12] }

In [402]:
student_info_df = pd.DataFrame(student_info_d)
student_info_df

Names  Age
0  Ronke   15
1  Uzezi   20
2    Ada   25
3   Josh   12

In [403]:

student_info_series = student_info_df['Names']
student_info_series

0    Ronke
1    Uzezi
2      Ada
3     Josh
Name: Names, dtype: object

In [404]:
# operating on pandas series
student_info_series.index

RangeIndex(start=0, stop=4, step=1)

In [405]:
student_info_series.values

array(['Ronke', 'Uzezi', 'Ada', 'Josh'], dtype=object)

In [406]:
student_info_df

Names  Age
0  Ronke   15
1  Uzezi   20
2    Ada   25
3   Josh   12

In [407]:
student_info_df.loc[0]

Names    Ronke
Age         15
Name: 0, dtype: object

In [408]:
ronke = student_info_df.loc[0]
ronke.index

Index(['Names', 'Age'], dtype='object')

In [409]:
student_info_df.loc[1, 'Age']

np.int64(20)

In [410]:
student_info_df.loc[1:2, ['Names', 'Age']]

Names  Age
1  Uzezi   20
2    Ada   25

In [411]:
student_info_df.loc[1:2]

Names  Age
1  Uzezi   20
2    Ada   25

In [412]:
student_info_df.loc[2:3]

Names  Age
2   Ada   25
3  Josh   12

In [413]:
student_info_df[ ['Names', 'Age']]

Names  Age
0  Ronke   15
1  Uzezi   20
2    Ada   25
3   Josh   12

In [414]:
student_info_df['Age'].mean()

np.float64(18.0)

## EXPLORATIVE DATA ANALYSIS

In [415]:
import numpy as np
import pandas as pd

In [417]:
data = pd.read_csv('IPO_24.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'IPO_24.csv'

In [418]:
# info about the data
data.info()

NameError: name 'data' is not defined

In [ ]:
data.head()

In [ ]:
data('IPO Price').dtype

## EDA (Continuation)

In [ ]:
data.head()

In [ ]:
data['Current'] = data['Current'].str.replace('$', ' ')
data['Current'] = data['Current'].str.replace('-', '0')
data['Current'] = data['Current'].astype(float)

In [ ]:
for element in data['Return']:
 print(element)

In [ ]:
def replace_only_dash(x):
  if x == '-':
    x = 0

  return x

In [ ]:
replace_only_dash('-2.0')

In [ ]:
replace_only_dash('-')

In [ ]:
data['Return'] = data['Return'].apply(replace_only_dash)

In [ ]:
data['Return'].values

In [ ]:
data['Return'] = data['Return'].str.replace('%', ' ')
data['Return'] = data['Return'].astype(float)

In [ ]:
data.head()

In [ ]:
data['IPO Price'] = data['IPO Price'].str.replace('$', '')

In [ ]:
data['IPO Price']

In [ ]:
mask = data['IPO Price'] == ' '
mask

In [ ]:
data['IPO Price'][mask]

In [ ]:
data['IPO Price'] = data['IPO Price'].str.replace('-', '0')
data['IPO Price'] = data['IPO Price'].str.replace(' ', '0')
data['IPO Price'] = data['IPO Price'].astype(float)

In [ ]:
#pd.to_datetime method

data['IPO Date'] = pd.to_datetime(data['IPO Date'])

In [ ]:
print(data['IPO Date'].dtype)

In [ ]:
data.head()

## Saving the clean data as csv

In [ ]:
data.to_csv("Cleaned_IPO__24.csv", index=False)

In [ ]:
pd.read_csv("Cleaned_IPO__24.csv")

In [ ]:
data.describe()

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.hist(data['IPO Price'], bins=5)
plt.show()

In [ ]:
plt.hist(data['Return'], bins=20, alpha=0.75, color='green')
plt.title("Distribution of Return")
plt.xlabel('Return')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()

In [ ]:
plt.boxplot(data['IPO Price'])
plt.show()

In [ ]:
plt.hist(data['IPO Price'], bins=20, label='IPO Price')
plt.hist(data['Return'], bins=50, label='Return')
plt.legend()
plt.show()